### ISSUE TITLE
Micro MinimOSD compatibility?

### ISSUE THREAD

**Issue by pfriedel** [Dvogonen/cyclop_plus_plus#1]
Is the only reason for the MinimOSD (instead of MicroMinimOSD) is because the guide taps vBat for power instead of the regulated rail that seems to be able to run all the way down to 5v from the Cyclops+ documentation?  I ask because I've got a couple of micros littering my workbench, but my only regular one is tied up.

**Comment by Dvogonen** [comment]
Yes, that is indeed the reason. The micro variant will probably work, but then you need to figure out yourself how to power it. Using the regulator on the receiver board might work, but both the voltage and the current draw close to the limit. 
A small separate regulator for the OSD board is another solution.
